#!/usr/bin/env ruby

require 'rubygems'
require 'commander'

class Blender
  include Commander::Methods

  def run
    program :name, 'blend'
    program :version, '0.0.1'
    program :description, 'Blend image'

    command :blend do |c|
      c.syntax = 'blend blend [options]'
      c.summary = ''
      c.description = ''
      c.example 'description', 'command example'
      c.option '--some-switch', 'Some switch that does something'
      c.action do |args, options|
        # Do something or c.when_called Blend::Commands::Blend
      end
    end

    run!
  end
end

Blender.new.run if $PROGRAM_NAME == __FILE__
